# Generated by Django 5.2.2 on 2025-12-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanelisscore', '0005_product_stock_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('mobileno', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('cartitems', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
