# Generated by Django 5.2.2 on 2025-12-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanelisscore', '0007_customers_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='customers',
            name='cartitemsandquantitu',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
