# Generated by Django 5.2.2 on 2026-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanelisscore', '0008_remove_customers_cartitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
