# Generated by Django 5.2.2 on 2026-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanelisscore', '0009_customers_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
