# Generated by Django 5.2.2 on 2026-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanelisscore', '0010_orders_merchant_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
